### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [jgudo/foodie#13]

**Comment by jgudo** [comment]
@idontknowletsaysomething  Could you tell me the steps to reproduce this issue? Everything seems fine to me. If possible, could you attach a screenshot also?

**Comment by idontknowletsaysomething** [comment]
![bugs](https://user-images.githubusercontent.com/11656661/121767985-4e4bbd80-cb79-11eb-8676-3486f97c1fae.gif)
Not sure whats causing it. 
![bug](https://user-images.githubusercontent.com/11656661/121768165-5ce6a480-cb7a-11eb-96d4-a44e73fbace5.JPG)

**Comment by jgudo** [comment]
Found the culprit. In my useEffect, I was assigning the value of bio directly to its value, so it sometimes assigns ``undefined`` if it really is undefined, so now I have to conditionally set an empty string if its value is falsey. 

```
useEffect(() => {
        setField({
            ...
            bio: profile.info?.bio || '',
           ..
        });

    }, [profile]);
```

I also have to optionally chain checking for its length 
``const [bioLength, setBioLength] = useState(200 - profile.info?.bio?.length || 0);``
